#
# Copyright (c) 2023-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    chart: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.labels.app }}
    spec:
      hostNetwork: true
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets}}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
            limits:
              cpu: 100m
              memory: 200Mi
        volumeMounts:
          - mountPath: /data/sys
            name: sys
      serviceAccountName: node-interface-metrics-exporter-sa
      volumes:
        - hostPath:
            path: /sys
            type: ""
          name: sys
