# Default values for node-interface-metrics-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: starlingx/metrics-exporter-api
  tag: stx.11.0-v1.0.0

namespace: node-interface-metrics-exporter
imagePullSecrets: default-registry-key

name: node-interface-metrics-exporter
labels:
  app: nime-app
