[metadata]
name = k8sapp-node-interface-metrics-exporter
summary = StarlingX sysinv extensions for node-interface-metrics-exporter
long_description = file: README.rst
long_description_content_type = text/x-rst
license = Apache 2.0
author = StarlingX
author-email = starlingx-discuss@lists.starlingx.io
home-page = https://www.starlingx.io/
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9

[files]
packages =
    k8sapp_node_interface_metrics_exporter

[global]
setup-hooks =
    pbr.hooks.setup_hook

[entry_points]
systemconfig.helm_applications =
    node-interface-metrics-exporter = systemconfig.helm_plugins.node_interface_metrics_exporter

systemconfig.helm_plugins.node_interface_metrics_exporter =
    001_node-interface-metrics-exporter = k8sapp_node_interface_metrics_exporter.helm.node_interface_metrics_exporter:NodeInterfaceMetricsExporterHelm

systemconfig.app_lifecycle =
    node-interface-metrics-exporter = k8sapp_node_interface_metrics_exporter.lifecycle.lifecycle_node_interface_metrics_exporter:NodeInterfaceMetricsExporterAppLifecycleOperator

[wheel]
universal = 1
