# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for Node Interface Metrics Exporter
name: node-interface-metrics-exporter
type: application
version: 0.1.0
